### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by sasq64** [yhirose/cpp-peglib#106]
1. The message given to parse_error seems to be ignored, is this intentional ?
2. Is there a way to start parsing at a specific rule ?
3. How does the '&' operator work ?
4. Could something like a `syntax_error` error exception be added, that directly ends parsing and reports the error ?

**Comment by sasq64** [comment]
Also I find myself just returning `semanticValues.token()` from a lot of actions. Maybe a grammar shortcut for this would be helpful? Or am I doing it wrong?

**Comment by yhirose** [comment]
Here are my answers:

> 1. The message given to parse_error seems to be ignored, is this intentional ?

Since I don't see you code, I can't answer your question. But the following unit test may show you what to do:

https://github.com/yhirose/cpp-peglib/blob/3c58f266351cd3f592d8431dff9e9e1526fa73f4/test/test2.cc#L613-L635

> 2. Is there a way to start parsing at a specific rule ?

No. cpp-peg always starts with the first rule.

> 3. How does the '&' operator work ?

You can see the official description in [the official paper](https://github.com/yhirose/cpp-peglib/blob/3c58f266351cd3f592d8431dff9e9e1526fa73f4/test/test2.cc#L613-L635.) by Bryan Ford. He can explain it better than I do. :)

_"The operators & and ! denote syntactic predicates [20], which provide much of the practical expressive power of PEGs. The expression ‘&e’ attempts to match pattern e, then unconditionally backtracks to the starting point, preserving only the knowledge of whether e succeeded or failed to match."_

> 4. Could something like a syntax_error error exception be added, that directly ends parsing and reports the error ?

No. Basically any syntax error should be detected only by the PEG parser itself. But cpp-peglib allows users to stop parsing by throwing an `parser_error` in a user action handler. You have already seen an example in my answer for your first question.

By the way, here are two real PEG grammar examples that I wrote for your rerefence:

* [Monkey programming language](https://monkeylang.org/)
https://github.com/yhirose/monkey-cpp/blob/master/engine/parser.hpp

* [PL/0](https://en.wikipedia.org/wiki/PL/0):
https://github.com/yhirose/pl0-jit-compiler/blob/master/pl0.cc

Also PEG Playground at https://yhirose.github.io/cpp-peglib could be helpful when designing a grammar.

Thanks for showing interest in this library!

**Comment by sasq64** [comment]
Re 4
The problem with just returning parse_error is that you loose the scope of the error, like the actual error (ie "symbol not defined")

But I have worked around this by catching by own `syntax_error` in my wrapper, and inserting the line_info from the SemanticWrapper into it.

**Comment by yhirose** [comment]
@sasq64, glad to hear that you found the workaround for your use case. I'll close it.

If the following 'user data' member `std::any d_` is added to `struct parse_error`, can it solve your 'scope of the error' issue?

```cpp
struct parse_error {
  parse_error() = default;
  parse_error(const char *s) : s_(s) {}
  parse_error(const char *s, any d) : s_(s), d_(std::move(d)) {}
  const char *what() const { return s_.empty() ? nullptr : s_.c_str(); }
  const any& data() const { return _d; }

private:
  std::string s_;
  any d_;
};
```

**Comment by sasq64** [comment]
I don't think so, since the error just means to continue parsing, and then another error can be thrown later as a side effect of the first...

**Comment by yhirose** [comment]
@sasq64, thank you for the reply. I probably don't fully understand what you are talking about.

Here is the code snippet where `parse_error` is handled in peglib.h:
https://github.com/yhirose/cpp-peglib/blob/3c58f266351cd3f592d8431dff9e9e1526fa73f4/peglib.h#L2507-L2517

So if the error position is smaller than the last remembered error position, the old one will be replaced with the new one. In other words, the cpp-peglib reports only the closest error to the beginning of the given source text.

I know the error strategy isn't great at all. At the same time a lot of PEG parsers also struggle with better error handling. I have to do more research about this area.

In order to understand the problem you encountered, is it possible for you to show me the smallest possible PEG grammar that causes the problem?

Thanks for you help!
