### ISSUE TITLE
Benchmarking grammar ?

### ISSUE THREAD

**Issue by sasq64** [yhirose/cpp-peglib#125]
Is there a way to benchmark your grammar?
To see if you have defined rules in a non-optimal way that causes peglib to do unnecessary work ?

**Comment by yhirose** [comment]
@sasq64, there isn't. I think the performance depend on not only grammar, but also particular context of source text. The only thing that cpp-peglib checks is to detect left recursive grammar that could cause infinite look. Is there any good algorithm or tool to benchmark regular expression grammar, so that we could apply it to PEG? Thanks!

**Comment by sasq64** [comment]
I was thinking maybe recording how much the parse has to backtrack, or parse the same bit of source multiple times.
I guess I could implement that myself with the trace callbacks ? Then form a histogram on which rules that where evaluated the most...

**Comment by yhirose** [comment]
@sasq64, sounds fantactic! Only thing that I request you is to make sure that no extra performance const should be added when trace callbacks are not set.

**Comment by yhirose** [comment]
@yhirose, I'll close it for now. Please let me know when you work on that.

**Comment by asmwarrior** [comment]
> @sasq64, sounds fantactic! Only thing that I request you is to make sure that no extra performance const should be added when trace callbacks are not set.

Typo: const should be cost.
