### ISSUE TITLE
token() in AST different from SemanticValues

### ISSUE THREAD

**Issue by sasq64** [yhirose/cpp-peglib#127]
It seems token() will returned the matched value from SemanticValues at any part in the tree, but in an AST it will only return something for the leaf nodes.
I don't know if this is intentional but it would be very practical to be able to access the matched text in non leaf nodes.

**Comment by yhirose** [comment]
@sasq64, thanks for the feedback. this is on purpose to reduce memory usage in an AST tree. In my usages so far, there is no need to access token text on non leaf nodes at all. In the next cpp17 version, we could extend it to non leaf nodes since the `token` member is now `std::string_view` that doesn't copy any source text.

**Comment by sasq64** [comment]
Incidentally I'm using the cpp17 branch so I didn't consider the fact that it was a space issue...
I'm recreating the contents by mean of position/size and the original source now instead.
