### ISSUE TITLE
Interaction between `%whitespace` and token boundary operators

### ISSUE THREAD

**Issue by dpacbach** [yhirose/cpp-peglib#128]
Hi, I've been playing around in the sandbox tool (https://yhirose.github.io/cpp-peglib/) and I can't seem to make sense of the behavior of the parser when I have both `%whitespace` and token boundary operators in the same rule.  For example, let's say that we have the source code:

`..a...b...c..`  (replace dots by spaces; github won't render spaces properly)

Then some setup:

```
ROOT <- TOP
A <- 'a'
B <- 'b'
C <- 'c'
%whitespace  <-  [ \t\r\n]*
```

Now we write `TOP` in various forms, yielding different parsing results that I can't explain:

1. `TOP <- 'a' 'b' 'c'`: successful parse, yielding `TOP (a...b...c..)`
2. `TOP <- <'a' 'b' 'c'>`: fails to parse; why?
3. `TOP <- <'a' B 'c'>`: fails to parse; why?
4. `TOP <- <A 'b' 'c'>`: successful parse, yielding `TOP (a...b...c..)`; why is this successful if # 3 was not?  Why does it include whitespace after c?
5. `TOP <- A <'b' C>`: fails to parse; why?
6. `TOP <- <A> B C`: successful parse, yielding `TOP (a...)`; why does it include whitespace after a?

Again, replace dots with spaces in the results since github seems to condense multiple spaces I had to write them as dots.  I am having a hard time making sense of the above... can you help?  I feel like there must be some key rule missing from the documentation that explains how the token boundary operators behave in the presence of `%whitespace` but also they seem to behave differently when there are literal strings inside the token boundary versus e.g. `A`, `B`, etc.

**Comment by yhirose** [comment]
@dpacbach, thanks for the excellent feedback! Some of them are actually bugs...

First of all, here is an example of the token boundary operator.

![image](https://user-images.githubusercontent.com/357397/98548729-d8d8e100-2267-11eb-9869-a184279eea18.png)

There are two purposes of the token boundary.

1) Concatenate characters to make up a token which is accessible with `tokens` member and `token` method on `SemanticValues`.

2) Cancel the `%whitespace` behavior inside the token

We can have more than one nested token operators as the above example. In this example, we can get token text without quotes with `token` method which focuses on the inner token boundary. The outer token boundary serves for canceling `%whitespace` behavior after  the first `"` character.

If we remove the outer token boundary, the result ends up loosing the spaces right after the opening quote character.

![image](https://user-images.githubusercontent.com/357397/98553544-b77af380-226d-11eb-9331-6f76f182e4cb.png)

> 1. `TOP <- 'a' 'b' 'c'`: successful parse, yielding `TOP (a...b...c..)`

This is an expected behavior.

> 2. `TOP <- <'a' 'b' 'c'>`: fails to parse; why?

This is an expected behavior, because the token operator cancels effect of `%whitespace`.

> 3. `TOP <- <'a' B 'c'>`: fails to parse; why?

This is an expected behavior for the same reason above.

> 4. `TOP <- <A 'b' 'c'>`: successful parse, yielding `TOP (a...b...c..)`; why is this successful if # 3 was not?  Why does it include whitespace after c?

This should fail for the same reason above. It's a bug.

> 5. `TOP <- A <'b' C>`: fails to parse; why?

This is an expected behavior, because the token operator cancels effect of `%whitespace`.

> 6. `TOP <- <A> B C`: successful parse, yielding `TOP (a...)`; why does it include whitespace after a?

This should fail for the same reason above. It's a bug.

I'll be working on the bugs sometime this month, and get back to you. Hope this explanation helps.

**Comment by dpacbach** [comment]
@yhirose Thank you for the explanation, that definitely helps.  I was missing the part about the token operator cancelling the effects of `%whitespace`.  Also thank you in advance for fixing the bugs!

**Comment by yhirose** [comment]
@dpacbach, I fixed the bugs. As for #6, it should actually be successful, but `Top (a...)` is incorrect. It now yields `TOP (a)` correctly.

![image](https://user-images.githubusercontent.com/357397/98574071-78f13300-2285-11eb-8fc7-b16bff3fb121.png)

I also updated the play ground site as well. (Please make sure that reload the page to reflect the fix.)
Please let me know if you find additional problems. Thanks!

**Comment by dpacbach** [comment]
Thank you again for the fix and the explanation, now it all makes sense!
