### ISSUE TITLE
Disable backtracking?

### ISSUE THREAD

**Issue by dpacbach** [yhirose/cpp-peglib#138]
Is it possible to disable backtracking?  I think my grammar does not require backtracking (i.e., the branch in the choice operator that is chosen can be known only from the first character).  So therefore, I think that if I could somehow disable backtracking in cpp-peglib that it would give me better error messages.

Currently cpp-peglib suffers from the poor error messages that are characteristic of backtracking.

**Comment by yhirose** [comment]
@dpacbach, thank you for the feedback, and sorry that cpp-peglib only gives the poor error report. Unfortunately, it's currently not possible to disable backtracking in cpp-peglib...

In order to support the feature, cpp-peglib needs to support 'cut operator'. You can see more detailed information in the following papers:
https://kmizu.github.io/papers/paste513-mizushima.pdf
http://ceur-ws.org/Vol-1269/paper232.pdf

The only popular PEG parser supporting the cut operator that I know of is [parboiled2](https://github.com/sirthias/parboiled2). It supports `a ~!~ b` operator. (Please let me know if you know more. In C++, even the most popular [PEGTL](https://github.com/taocpp/PEGTL) doesn't support it, I think.)
When I have time in the future, I'll try to implement it in cpp-peglib. Or a pull request is always welcome. :)

I have recently added the new [error report and recovery feature](https://github.com/yhirose/cpp-peglib#error-report-and-recovery). If you need custom error messages and error recovery, you may be interested in it. Since I had to impement it quickly in my project at work, I didn't have time to provide comprehensive document in README. But you can find more information about the concept of this error recovery system in [this paper](https://arxiv.org/pdf/1806.11150.pdf). I just implemented what the paper suggests. You can also find their real implementation [here](http://www.inf.puc-rio.br/~roberto/lpeg/).

Hope it helps!

**Comment by yhirose** [comment]
#24

**Comment by yhirose** [comment]
@dpacbach, I am just curious how bad the PEG substantial backtracking performance is.

Could you show me your PEG grammar for my benchmark test, and also give me your thought how much performance improvement you could gain with disabling the backtracking? (I personally have not encountered any performance problem in my projects so far. I just would like to know what kind of tasks can lead to such a problem.)

If I feel that the cur operator can improve the performance problem greatly in many cases, I'll consider implementing it.
Thanks for your help.

**Comment by dpacbach** [comment]
@yhirose Thanks for the response.  My input files are relatively small, so I am not concerned with performance.  I was hoping to disable backtracking in order to improve error messages.  By that I mean, for example if I have this:
```
FOO <- A / B / C / D
```
And let's say that `A` itself is a complicated structure.  If the user intends to write an `A` but makes a syntax error deep inside, then it will backtrack out to the level of `FOO` and will report the error at the "wrong" place (much earlier in the input than the actual error).

If you still would like to see my grammar I can give it to you, but again, I am not concerned with performance, only quality error reporting, which currently is not working ideally because the choice operator `/` combined with backtracking tends to lose information about the error.

In the "Error report and recovery" section, I see that you mentioned:

> cpp-peglib supports the furthest failure error posision report

This sounds like something that might help me if I can get the position of the furthest failure.  Can you explain more about what this means and how to use it?  There was an example that followed, but I wasn't sure if that (recovery operators) is what you were referring to.

**Comment by yhirose** [comment]
@dpacbach, "the furthest failure error position report" is the default error report algorithm that [the original Bryan Ford's paper](https://bford.info/pub/lang/peg.pdf) suggests. cpp-peglib implements the algorithm as default error strategy.

In your example, if all of four rules fail in FOO, then the furthest error position in one of the rules will be reported as the error position of FOO. It might not be the best error position, but this heuristic error strategy works pretty well in most situations according to the paper. But it seeks the algorithm doesn't work well with your grammar unfortunately...

More precisely in your example, when parsing fails in `A`, it just save the syntax error position as a candidate, then backtrack to the input position of `FOO` and tries `B`. If parsing also fails in `B`, if the error position is smaller than the saved position, the parser just ignores it, otherwise update the candidate error position with it. The parser tries the same for `C` and `D`. I think you can find better explanation in Bryan Ford's paper. Anyway, the furthest failure error position strategy is heuristic, and sometimes don't give what we expect...

As I mentioned above, I implemented the additional error recovery/report system that allows custom messages and can report more than one error when parsing. I don't have enough time to explain it, you can find better explain about it from ["Syntax Error Recovery in Parsing Expression Grammars" paper](https://arxiv.org/pdf/1806.11150.pdf) by Sergio Medeiros and Fabio Mascarenhas.

**Comment by dpacbach** [comment]
> "the furthest failure error position report" is the default error report algorithm that the original Bryan Ford's paper suggests. cpp-peglib implements the algorithm as default error strategy.

Ok it looks like that was a new feature recently added.  I updated my copy of cpp-peglib to get that feature and ran some tests, and that seems to fix my problem, including the one in my example above with `FOO`.  I understand it is not perfect in all cases, but I think this furthest-failure strategy will work for me in most cases.  Thanks!

**Comment by mqnc** [comment]
I am not too deep in the parsing business but it sounds to me like you're more after a simple LL(1) parser.

Also, a strategy that you can use for errors using peglib is this:

FOO <- A / B / C / D / FOO_ERROR
A <- A1 / A2 / A3 / A_ERROR
A1 <- A1_1 / A1_2 / A1_3 / A1_ERROR

and so on.

It obfuscates your grammar a bit but you will never backtrack (I think) and you can have a meaningful error message in each individual case. You can either stop parsing when you reached one of the error tokens or you make them capture everything until the end of the line for example and then you can report multiple errors for one file.

**Comment by dpacbach** [comment]
@mqnc Thanks for that suggestion, I will keep that in mind if I ever need it (i.e., putting `FOO_ERROR` at the end of the choice statement).  For now, it appears that the new "furthest-failure" mechanism that @yhirose implemented is working fine for me in that it gives me error messages at the correct location.  This is nice because we can get the correct error messages without having to effectively disable backtracking.
