### ISSUE TITLE
Is it okay for basic example to take ~30 seconds to compile?

### ISSUE THREAD

**Issue by exoticus** [yhirose/cpp-peglib#151]
Just including peglib.h to a barebones project adds 20+ seconds of build time, trying to compile the basic Readme example takes 28~30 seconds. Tested on both gcc/clang on linux, and clang on macOS. I wonder if that's normal?

**Comment by yhirose** [comment]
@exoticus, I honestly admit that cpp-peglib is slow to compile, since it uses C++ meta programming techniques. The benefit of this approach is that actual user's source code using this library can be much more concise. So I am more focusing on readability than building time. 

Here is my result on MacBook 2016 (1.2 GHz Dual-Core Intel Core m5, 8 GB 1867 MHz LPDDR3). 

```
~/Projects/cpp-peglib/build$ time make calc
[ 50%] Building CXX object example/CMakeFiles/calc.dir/calc.cc.o
[100%] Linking CXX executable calc
[100%] Built target calc

real	0m10.245s
user	0m9.815s
sys	0m0.358s
```

Yes, it's slow... Anyway, if your project is very much concerned with building time, cpp-peglib is not a library for you probably. It would be better for you to try out other C++ PEG libraries like PEGTL.

Thanks for your understanding!
