### ISSUE TITLE
Tree building notation (III) 

### ISSUE THREAD

**Issue by g40** [yhirose/cpp-peglib#16]
Another idea for a tree-annotated grammar. Note the **N:** prefix. The 0'th node becomes the parent. Then its children are assigned in numerical order. So this makes it really easy to create new nodes with an arbitrary number of children. (Yuji, this is only a partially-considered scribble right now. I'm just posting it here for more brain fodder)

```
                # annotation equivalent to the default parse tree construction
        0:RESULT_LIST       <- 1:RESULT (',' 2:RESULT)*
        RESULT          <- (NAMED_RESULT / ANON_RESULT)
                # ASSIGNMENT_OP becomes parent to IDENTIFIER and ANON_RESULT
        NAMED_RESULT    <- 1:IDENTIFIER 0:(ASSIGNMENT_OP/HASH_OP) 2:ANON_RESULT
        ANON_RESULT     <- (0:STRING_LITERAL / BRACE_LIST / BRACK_LIST)
                # i.e. here we end up with a new RESULT_LIST node, not a BRACE_LIST
        BRACE_LIST      <- '{' (0:RESULT_LIST)* '}'
        BRACK_LIST      <- '[' (0:RESULT_LIST)* ']'
        ASSIGNMENT_OP   <- < '=' >
        HASH_OP         <- < '#' >
```

**Comment by g40** [comment]
Hi Yuji, any more thoughts on this? BTW if you wish to take discussion elsewhere my email is g4 <at> novadsp.com

**Comment by yhirose** [comment]
Hi Jerry,

Sorry for the late reply. I haven't found time to think about the topic due to busy days lately.

I'll start making a branch for the N:prefix idea when things settle down. I hope we could find enough insight about the extended grammar with this experiment. I'll find as many use cases as possible, so that the grammar could cover most situations that users could experience.

Also I would like to keep the code base simple and keep the same performance. I guess we could check them with the experiment as well.

Since it will definitely be the biggest change since the PEG lib was born, I would like to spend enough time to make the best one in the main branch.

Thanks for your advice and patience on this matter!!
Yuji

**Comment by yhirose** [comment]
Added this reference to #16.
