### ISSUE TITLE
Whitespace is ignored before it can be look-ahead tested

### ISSUE THREAD

**Issue by kfsone** [yhirose/cpp-peglib#204]
We're using a quasi-ini styled file format, and one of the conditions I'd like to assert is that the section header lines have nothing but a newline after the close ']'.

```
section <- "[" identifier "]" &'\n'
```

Almost nowhere else do I care about newlines, or the grammar gets difficult, unfortunately the discard of whitespace appears to prevent doing this kind of lookahead test:

![image](https://user-images.githubusercontent.com/323009/169733495-a409332c-8ee4-423a-b5a0-7b59300cda9e.png)

**Comment by yhirose** [comment]
@kfsone, you are correct since `%whitespace` has higher priority and eats white spaces after tokens before a following operator gets evaluated. If you need to fully control white space behavior, you can't use `%whitespace`, rather you have to do it manually. `%whitespace` and `%word` can be used for common situations, but don't cover all the possible use cases like yours.
