### ISSUE TITLE
[Question] what does the underscore means in switch cases

### ISSUE THREAD

**Issue by zjhmale** [yhirose/cpp-peglib#26]
Hi, I'm currently reading the pl0 language example and find something really confused, like [here](https://github.com/yhirose/cpp-peglib/blob/master/pl0/pl0.cc#L438), in this file, all the switch cases are following up with an underscore, is this a DSL from this lib or a new C++11 feature? Thanks in advance :)

**Comment by yhirose** [comment]
@zjhmale, I am glad you noticed the neat C++11 technique!

The literals are actually not `const char*` strings, but `unsigned int` values. That's why we can use them in `switch` statement.

It looks weird. But it's valid C++11 code accomplished with C++11 [User-defined literals](http://en.cppreference.com/w/cpp/language/user_literal) and `constexpr`.
https://github.com/yhirose/cpp-peglib/blob/master/peglib.h#L2149-L2159

You can find more information about the technique in the following articles:
https://dev.krzaq.cc/post/switch-on-strings-with-c11/
https://stackoverflow.com/questions/2111667/compile-time-string-hashing

Hope it helps.
