### ISSUE TITLE
Issue in parser reuse

### ISSUE THREAD

**Issue by 95A31** [yhirose/cpp-peglib#260]
Hello,

I am developing a frontend of a small language. For debugging purpose, I would like to print the AST and then get the result of the parsing obtained with my actions. To my understanding, it is not possible doing that with the same parser instance because the method `enable_ast()` adds its own actions. I am wondering if it is safe to introduce a method like the following: 

```cpp
void reset_actions()
{
  for (auto & [_, rule]  :  *grammar_)
  {
    ~rule.action;
    rule.action = Action();
  }
}
```
Cheers

**Comment by yhirose** [comment]
@95A31, thanks for your feedback.

> To my understanding, it is not possible doing that with the same parser instance because the method enable_ast() adds its own actions.

You are correct. I recommend to have two parser instances with the same grammar and use one of them as a debug parser with AST mode. I think it's better since the parser with AST mode should be slower since it has lots of overhead which is not necessary for the production parser.

Your reset method may work though, `~rule` looks suspicious to me. It doesn't reset the object state, since it sets 'true' instead of 'false' to `ignoreSemanticValue` member variable in a Definition object.

Hope it helps!
