### ISSUE TITLE
utf-8 support

### ISSUE THREAD

**Issue by mjsurette** [yhirose/cpp-peglib#30]
As part of a larger project which uses utf-8 internally for which I had to read files which could be utf-8 or utf-16.  While the project is not ready for posting I have broken off some utilities which includes utf conversion routines (and a link to where I got the information in the header file).  I hope that this may be of use to you in your efforts.

https://github.com/mjsurette/easyUtils

Mike

**Comment by yhirose** [comment]
@mjsurette, thanks for the information of your library. In fact, I have already written my own Unicode library which also includes UTF conversion functions. 😄 
https://github.com/yhirose/cpp-unicodelib#encoding

Since the input interfaces of peglib are `const char*` and `std::string`, it accepts only 8-bit character encoding such as ASCII or UTF-8. I just would like to stick to it for simplicity, rather than introducing interfaces of other character sizes.

One remaining problem with the 8-bit approach is how to properly handle `.` PEG operator (It is in the [TODO list](https://github.com/yhirose/cpp-peglib#todo).). It should match `any character`. But it should be just a single byte or a valid UTF-8 byte sequence or a valid UTF-8 grapheme cluster. Since it's enough for all my projects so far that `.` matches a single byte, I just leave it for now.

Anyway, thanks for your interest in this library!
