### ISSUE TITLE
C++11 Version?

### ISSUE THREAD

**Issue by hannes** [yhirose/cpp-peglib#301]
@yhirose Excellent work on this library, we were wondering if it might be possible to sponsor development of a C++11 or 14 compatible version? Could you ping me at hannes@duckdblabs.com - thanks!

**Comment by yhirose** [comment]
@hannes thank you for the request, but I not planning to go back to support C++11 or C++14. Here is the commit when I moved to C++17 from C++11 about 4 years ago. C++17 supports a number of nice language features and standard libraries, and I simplified the peglib.h greatly. Since this is my personal project maintained in my limited time, code simplicity is very important to me. :)

https://github.com/yhirose/cpp-peglib/commit/b26e2477ffe34deb37b92e9fc609a3a16cd55ec1#diff-5ca9fbaaa7735ba1e069e166f23ab9553fa99963defa0cd7762b4604e8f52c5d
