### ISSUE TITLE
Support left recursion

### ISSUE THREAD

**Issue by mqnc** [yhirose/cpp-peglib#39]
After discovering the whole issue with left recursion and noticing that I can't live without it, I wonder if you are planning to implement it. I have found that some PEG parsers support it using different techniques:

https://github.com/axilmar/parserlib/blob/master/LEFT_RECURSION.txt
https://github.com/PhilippeSigaud/Pegged/wiki/Left-Recursion

**Comment by yhirose** [comment]
@mqnc, thanks for the feedback. As you see in the code, cpp-peblib doesn't support left recursion. It only detects left recursion in a given grammar and report it. (Please see [the code](https://github.com/yhirose/cpp-peglib/blob/master/peglib.h#L2120).)

Right now, I don't have a plan to implement it, since I don't see any necessity of left recursion grammar support in my projects. But I may try to do so in the future, when I meet a situation where I cannot avoid left recursion.

Just for my curiosity, what kind of PEG grammar are you using? Cannot it be transformed to a traditional PEG grammar without left recursion?

Thank you!

**Comment by mqnc** [comment]
Hi!

I don't understand how the left-recursion report works. If I have a grammar with left recursion, it fails during initialization of the parser, so I don't get to parse something where it could write that into the log.

What I'm doing with it...
In short, I want to have my own programming language on top of C++: [https://github.com/mqnc/fiascode](https://github.com/mqnc/fiascode)
It started with a bunch of preprocessor macros, they were not powerful enough so I moved to pre-preprocessing with regular expressions in Python, I also quickly ran into the limitations of this so I started to work with an actual parser. I didn't know anything about parsing but parsley's github readme said "Parsley is a parsing library for people who find parsers scary or annoying." so it seemed like the right tool.
The long story before the short story is here: [https://www.codeproject.com/Messages/5496927/What-is-the-fastest-and-bestest-programming-langua.aspx](https://www.codeproject.com/Messages/5496927/What-is-the-fastest-and-bestest-programming-langua.aspx)

Because Parsley (PEG for Python) became too slow already, I want to move to C++.

So far I can mix my code with c++, have the parser recognize my keywords and just pass through everything else that it doesn't understand. That's why I didn't need left recursion before. But now I want to do it the other way around, have a complete language and mark verbatim c++ with a special keyword. So I have to be able to parse a - b - c into (a - b) - c and reading about the difficulties of that on wikipedia, I don't know if freeing my grammar from left recursion by restructuring it works. It changes the structure of the AST and I want to support custom operators where it parses a @ b @ c into f(f(a,b),c).

I had a look at your code because I was thinking about implementing left recursion myself but it's a lot and it's not so easy to understand for me. I think I will make a list of questions and put them here if that's ok for you. In the long run I also want Unicode support but I think that can easily be implemented using your current version of the parser and just not using the '.' but some rules that understand Unicode instead.

I was already looking for other parsers (sorry :P) but I want to use PEG because I like how intuitive it is and I also want the syntax to be a string and not constructed from c++ operators. So if I don't want to move to D and use pegged, I guess peglib is my best bet.

**Comment by mqnc** [comment]
A friend just showed me how to do left-associativity in parsers that don't support left recursion.
```
const auto syntax = R"(
	# Grammar for Calculator...
	Additive <- (Multitive < ('+' / '-') >)* Multitive
	Multitive <- (Primary < ('*' / '/') >)* Primary
	Primary <- '(' Additive ')' / Number
	Number <- < [0-9]+ >
	%whitespace <- [ \t]*
)";
```
Maybe you could change that in your calculator demo also. It's not necessary since your code works as a simple example but in my naive newbeeness I took it as a reference and thought that's how it has to be done and that I need left-recursion if I want left-associativity.

So it seems I don't need left recursion anymore after all :)

**Comment by yhirose** [comment]
Since you don't need the left recursion, the following is just for your information.

When it comes to the left-recursion detection, I use [`peglint`](https://github.com/yhirose/cpp-peglib/tree/master/lint). 

```peg
# In left-recursion.peg
S   <- E eoi
E   <- E '+n' / 'n'
eoi <- !.
```

```bash
> peglint left-recursion.peg 
left-recursion.peg:2:8: 'E' is left recursive.
```

Also if you are interested in more realistic examples, you could check the following my personal projects:
 * [PL/0 JIT compiler](https://github.com/yhirose/pl0-jit-compiler) - [grammar](https://github.com/yhirose/pl0-jit-compiler/blob/master/pl0.cc#L23-L59)
 * [Culebra language](https://github.com/yhirose/culebra) - [grammar](https://github.com/yhirose/culebra/blob/master/include/interpreter.h#L10-L100)

Both grammars don't rely on left-recursion, but handle operator associativity properly without any problem. (Unary operators (right-associativity: '-', '+') and binary operators (left-associativity: '-', '+', ''/', '*')) Also the grammars don't look complicated in my opinion.

So far, I didn't find any need for the left recursion support in my all projects. Also you may be interested in the comment in the popular [PEG.js](https://github.com/pegjs/pegjs) project.
* [Add support for left recursion #231](https://github.com/pegjs/pegjs/issues/231)
* [JavaScript grammar without left recursion](https://github.com/pegjs/pegjs/blob/master/examples/javascript.pegjs)
So unless the grammar of your language goes too complicated (or more complicated than JavaScript), I guess the left-recursion won't be necessary.

Also if you are looking for an other PEG library, you should check [PEGTL](https://github.com/taocpp/PEGTL). That's the most popular C++ PEG parser.

Hope your project will go well!
