### ISSUE TITLE
RFE: use string_view into original string

### ISSUE THREAD

**Issue by toddlipcon** [yhirose/cpp-peglib#81]
When using AST mode, each token ends up creating a std::string, which is a bit inefficent, particularly on some C++ ABIs where there is no small-string optimization. It seems like it would be better to use string_view (or a user-specificable class) to reference the bytes of the original string.

**Comment by toddlipcon** [comment]
Perhaps the workaround is to just implement my own equivalent of enable_ast.

**Comment by yhirose** [comment]
@toddlipcon, thanks for the observation. You are talking about this line, right?

https://github.com/yhirose/cpp-peglib/blob/c0d2318b1582b0679618d53ede8bf9c98d7f06c8/peglib.h#L3098

It would be great if std::string_view can be used, but it's available from C++17. Since the library already provides peg::any, peg::string_view could be added to it as well.  Another solution is to use a pointer to the original text and length of the token, but sounds a bit dangerous...

> Perhaps the workaround is to just implement my own equivalent of enable_ast.

Another workaround is to provide your own Ast node type to enable_ast as a template parameter. You can make your own Ast node class based on AstBase, which can take Annotation where you could put anything you need like 'pointer and length for token'. Then, you can just ignore the token string member variable in AstBase.

**Comment by toddlipcon** [comment]
yep, that is one of the members here. I could make my own base class, but that won't avoid the performance hit of constructing the token here.

**Comment by yhirose** [comment]
I just wonder how much `token` affects the performance of making the AST tree. It probably depends on grammar and source text. What is the average length of `token` in your case? Is it pretty long?

**Comment by yhirose** [comment]
@toddlipcon, done with [cpp17 branch](https://github.com/yhirose/cpp-peglib/tree/cpp17). The library now uses `std::string_view`, so that it can avoid unnecessary memory copy. Unfortunately, this is breaking change, and users will need to adjust their code base to match the new interface.

This branch will be merged sometime this month. Hope you will enjoy it!

**Comment by sasq64** [comment]
I am very exited about this change, since a benchmarked parsing a very large file recently and around 40% time seemed to be spent creating strings.

I tried using the cpp17 branch, modigying my code to deal with the new `token()` but parsing fails. Anything one should thing about when trying this new branch ?

**Comment by sasq64** [comment]
You changed the grammar example for precedence parsing in the Readme, is there a new way to do this ?

**Comment by sasq64** [comment]
Turned out it was my fault, I had a use-after-free that triggered the problem in the parser.
Now it works great! A lot faster and benchmarking show basically all time is spent in Ope::parse as I expect.
