### ISSUE TITLE
shared_ptr used unnecessarily

### ISSUE THREAD

**Issue by toddlipcon** [yhirose/cpp-peglib#82]
In looking at peglib performance I noticed that a lot of cost is going into managing shared_ptrs. Given that parsing is single-threaded, it seems odd that most of the internal structures and collections (and AST support) are based on shared_ptr. Could we replace many of these with unique_ptrs?

Similarly, could we use an arena allocator for all of the structures that are created once per parse and then destructed together at the end? that would improve cache locality and avoid allocator contention.

**Comment by ColinH** [comment]
Using `unique_ptr` instead of `shared_ptr` seems to be easy in at least one case, that is changing `Context::value_stack` to a `std::vector<std::unique_ptr<SemanticValues>>`, and adapting `Context::push()` to the change, compiles and runs the included tests just fine (unfortunately changing to `std::vector<SemanticValues>` doesn't work, the tests segfault and I couldn't immediately spot why).

For `std::shared_ptr<Ope>` it appears to be more complicated, the ownership isn't quite as obvious and some of the classes derived from `Ope` use `std::enable_shared_from_this`, might be harder and require more refactoring if it can be done at all within the current design with which I am admittedly not very familiar.

(Btw, I'm not quite sure what the presence or absence of multi-threading has to do with `shared_ptr` inasmuch as the question of object ownership might not be clear cut even within a single thread...?)

On a performance-related note, there are some places where strings are copied instead of moved, e.g. the constructor of `LiteralString` could take a `std::string&&` instead of `const std::string&` and move it into `lit_` if the functions `lit()` and `liti()` are also changed to move their argument string `s`.

**Comment by toddlipcon** [comment]
I have a fork on GitHub which has a bunch of the above improvements. The vector of SenanticValues didn't work because of pointer stability, but changing it to deque works ok and avoids allocation and indirection overhead.

**Comment by yhirose** [comment]
@toddlipcon, thanks for working on replacing `std::shared_ptr` with `std::unique_ptr`. I think it's good idea. Only thing is that `std::make_unique` is available from C++14. Since cpp-peglib is **C++11** library, we should provide our own version of `make_unique` for C++ 11.  cpp-peglib already takes the approach for `std::any` which is available from C+17. Please check what `PEGLIB_USE_STD_ANY` does for more detail.

**Comment by yhirose** [comment]
I made a simple CSV parser with cpp-peglib and parse a huge csv data to measure performance with the Instruments tool on Xcode.

I tried first to make the suggested change to use `std::unique_ptr<SemanticValues>` instead of `std::unique_ptr<SemanticValues>`, but it was actually slower to use std::unique_ptr. So I reverted.

Then I tried to another constructor with `std::string&&` to `lit` and `ilit`, but it didn't make any performance difference. (I committed it to the master anyway, since it didn't make the performance worse.)

After I tried several different things based on the report from the Instruments, I made the following simple changes and improved performance 20% better:

https://github.com/yhirose/cpp-peglib/blob/10cc75d5033a82c9c0e8f983558aee5fefca19ab/peglib.h#L931

https://github.com/yhirose/cpp-peglib/blob/10cc75d5033a82c9c0e8f983558aee5fefca19ab/peglib.h#L937

https://github.com/yhirose/cpp-peglib/blob/10cc75d5033a82c9c0e8f983558aee5fefca19ab/peglib.h#L965

It was a pretty interesting experience to see that the profiler showed me the actual performance bottle necks that I didn't even think of.

Anyway, thanks for your suggestions!
